<a href="https://colab.research.google.com/github/NohaOmar20/Machine-Learning-Projects/blob/main/KNN_Classification_%26LogisticRegression_using_Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset link: https://www.kaggle.com/competitions/titanic

In [1]:
import pandas as pd

In [22]:
data=pd.read_csv('train.csv')

In [23]:
data.shape # size of data

(891, 12)

In [24]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
data.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [26]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [27]:
data=data.drop(["PassengerId","Pclass","Name","Cabin","Ticket"],axis=1)

In [28]:
data['Age'] = data['Age'].fillna(data['Age'].mean())

In [29]:
cols=['SibSp','Parch','Fare']
for col in cols:
  data[col].fillna(data[col].median,inplace=True)

In [30]:
data['Embarked'].fillna("U",inplace=True)

/tmp/ipython-input-2551906819.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Embarked'].fillna("U",inplace=True)

In [31]:
data['Sex']=data['Sex'].map({'male':1,'female':0})


data['Embarked']=data['Embarked'].map({'S':0,'C':1,'Q':2,'U':3})

In [32]:

X=data[['Sex','Age','SibSp','Parch','Fare','Embarked']]
y=data['Survived']

In [33]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.75,random_state=0)

**KNN**

In [34]:
from sklearn.neighbors import KNeighborsClassifier

knn_model= KNeighborsClassifier(n_neighbors=4)
knn_model.fit(X_train,y_train)

y_pred = knn_model.predict(X_test)

In [35]:
pd.DataFrame({'Y_Test':y_test, 'Y_Pred': y_pred})

     Y_Test  Y_Pred
495       0       0
648       0       0
278       0       0
31        1       0
255       1       0
..      ...     ...
167       0       0
306       1       1
379       0       0
742       1       0
10        1       1

[223 rows x 2 columns]

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7174887892376681

**Logistic Regression**

In [37]:
from sklearn.linear_model import LogisticRegression

logreg_model = LogisticRegression()
logreg_model.fit(X_train, y_train)

y_pred = logreg_model.predict(X_test)

In [38]:
pd.DataFrame({'Y_Test':y_test, 'Y_Pred': y_pred})

     Y_Test  Y_Pred
495       0       0
648       0       0
278       0       0
31        1       1
255       1       1
..      ...     ...
167       0       0
306       1       1
379       0       0
742       1       1
10        1       1

[223 rows x 2 columns]

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7757847533632287

In [40]:
coefficients = logreg_model.coef_
print(coefficients)

[[-2.53840531 -0.02199025 -0.40273126 -0.14580227  0.01289136  0.09522116]]